jwt.lo: /mnt/d/document/www/zephir/jwt/ext/jwt.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/jwt.c -o jwt.lo 
kernel/main.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /mnt/d/document/www/zephir/jwt/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/kernel/exit.c -o kernel/exit.lo 
jwt/exception/domainexception.lo: /mnt/d/document/www/zephir/jwt/ext/jwt/exception/domainexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/jwt/exception/domainexception.zep.c -o jwt/exception/domainexception.lo 
jwt/exception/invalidargumentexception.lo: /mnt/d/document/www/zephir/jwt/ext/jwt/exception/invalidargumentexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/jwt/exception/invalidargumentexception.zep.c -o jwt/exception/invalidargumentexception.lo 
jwt/exception/jsonexception.lo: /mnt/d/document/www/zephir/jwt/ext/jwt/exception/jsonexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/jwt/exception/jsonexception.zep.c -o jwt/exception/jsonexception.lo 
jwt/exception/tokenexception.lo: /mnt/d/document/www/zephir/jwt/ext/jwt/exception/tokenexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/jwt/exception/tokenexception.zep.c -o jwt/exception/tokenexception.lo 
jwt/token.lo: /mnt/d/document/www/zephir/jwt/ext/jwt/token.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/jwt/token.zep.c -o jwt/token.lo 
jwt/utils.lo: /mnt/d/document/www/zephir/jwt/ext/jwt/utils.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/mnt/d/document/www/zephir/jwt/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /mnt/d/document/www/zephir/jwt/ext/jwt/utils.zep.c -o jwt/utils.lo 
$(phplibdir)/jwt.la: ./jwt.la
	$(LIBTOOL) --mode=install cp ./jwt.la $(phplibdir)

./jwt.la: $(shared_objects_jwt) $(JWT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_jwt) $(JWT_SHARED_LIBADD)

